DgraphURL: 192.168.215.3:9080
ExportPath: ./data
DebugPath: ./log
PostgresHost: 192.168.215.2
PostgresPort: 5432
PostgresDBName: postgres
PostgresUser: postgres
PostgresPassword: ultratop
PostgresSchema: cimgraph
old: user=postgres password=ultratop host=192.168.215.2 port=5432 dbname=postgres

