/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 03-Oct-2025 14:21:50 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

SET SCHEMA 'cimgraph';
DROP SEQUENCE IF EXISTS seq
;

DROP SEQUENCE IF EXISTS seq
;

/* Drop Tables */

DROP TABLE IF EXISTS object CASCADE
;

DROP TABLE IF EXISTS predicate CASCADE
;

DROP TABLE IF EXISTS resource CASCADE
;

/* Create Tables */

CREATE TABLE object
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('seq'::text)::regclass),
	type varchar(100) NOT NULL,
	rdfid varchar(50) NOT NULL,
	valid_from timestamp with time zone NOT NULL,
	valid_to timestamp with time zone NOT NULL
)
;

CREATE TABLE predicate
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('seq'::text)::regclass),
	type varchar(50) NOT NULL,
	value_str text NULL,
	value_flt double precision NULL,
	resource varchar(50) NULL
)
;

CREATE TABLE resource
(
	object_id bigint NOT NULL,
	predicate_id bigint NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE object ADD CONSTRAINT "PK_object"
	PRIMARY KEY (id)
;

CREATE INDEX "IDX_type" ON object (type ASC)
;

ALTER TABLE predicate ADD CONSTRAINT "PK_predicate"
	PRIMARY KEY (id)
;

CREATE INDEX "IDX_type" ON predicate (type ASC)
;

ALTER TABLE resource ADD CONSTRAINT "PK_resource"
	PRIMARY KEY (object_id,predicate_id)
;

CREATE INDEX "IXFK_resource_object" ON resource (object_id ASC)
;

CREATE INDEX "IXFK_resource_predicate" ON resource (predicate_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE resource ADD CONSTRAINT "FK_resource_object"
	FOREIGN KEY (object_id) REFERENCES object (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE resource ADD CONSTRAINT "FK_resource_predicate"
	FOREIGN KEY (predicate_id) REFERENCES predicate (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE seq INCREMENT 1 START 1
;

CREATE OR REPLACE PROCEDURE insert_subject( type varchar(100),
                                rdfid varchar(50),
                                valid_from timestamp with time zone,
                                valid_to timestamp with time zone,
                                ret_id OUT bigint)
LANGUAGE plpgsql
AS $$
BEGIN
	INSERT INTO object(type,
                        rdfid,
                        valid_from,
                        valid_to)
	VALUES (type,
            rdfid,
            valid_from,
            valid_to)
	RETURNING id AS ret_id;
END;
$$