/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 10-Nov-2025 17:17:03 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */
SET SCHEMA 'cimgraph'

DROP SEQUENCE IF EXISTS association_id_seq
;

DROP SEQUENCE IF EXISTS attribute_id_seq
;

DROP SEQUENCE IF EXISTS class_id_seq
;

DROP SEQUENCE IF EXISTS enum_id_seq
;

DROP SEQUENCE IF EXISTS enumvalue_id_seq
;

DROP SEQUENCE IF EXISTS rdfs_id_seq
;

DROP SEQUENCE IF EXISTS rdfsattribute_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS association CASCADE
;

DROP TABLE IF EXISTS attribute CASCADE
;

DROP TABLE IF EXISTS class CASCADE
;

DROP TABLE IF EXISTS enum CASCADE
;

DROP TABLE IF EXISTS enumvalue CASCADE
;

DROP TABLE IF EXISTS rdfs CASCADE
;

DROP TABLE IF EXISTS rdfsattribute CASCADE
;

DROP TABLE IF EXISTS subclass CASCADE
;

/* Create Tables */

CREATE TABLE association
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"association_id_seq"'::text)::regclass),
	parent_id bigint NOT NULL,
	child_id bigint NOT NULL,
	name varchar(100) NOT NULL,
	label varchar(100) NULL,
	multimin integer NOT NULL,
	multimax integer NOT NULL,
	comment text NULL,
	range varchar(100) NULL,
	inverserole varchar(100) NULL,
	used boolean NOT NULL
)
;

CREATE TABLE attribute
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"attribute_id_seq"'::text)::regclass),
	class_id bigint NOT NULL,
	name varchar(100) NOT NULL,
	label varchar(100) NULL,
	datatype varchar(100) NOT NULL,
	mandatory boolean NOT NULL,
	comment text NULL
)
;

CREATE TABLE class
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"class_id_seq"'::text)::regclass),
	name varchar(100) NOT NULL,
	label varchar(100) NULL,
	comment text NULL,
	rdfs_id bigint NOT NULL
)
;

CREATE TABLE enum
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"enum_id_seq"'::text)::regclass),
	name varchar(100) NOT NULL,
	label varchar(100) NULL,
	comment text NULL,
	rdfs_id bigint NOT NULL
)
;

CREATE TABLE enumvalue
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"enumvalue_id_seq"'::text)::regclass),
	enum_id bigint NOT NULL,
	name varchar(100) NOT NULL,
	comment text NULL
)
;

CREATE TABLE rdfs
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"rdfs_id_seq"'::text)::regclass),
	rdftype varchar(100) NOT NULL,
	version varchar(50) NOT NULL,
	created_time timestamp with time zone NOT NULL
)
;

CREATE TABLE rdfsattribute
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"rdfsattribute_id_seq"'::text)::regclass),
	rdfs_id bigint NOT NULL,
	name varchar(100) NOT NULL,
	value text NOT NULL
)
;

CREATE TABLE subclass
(
	master_id bigint NOT NULL,
	sub_id bigint NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE association ADD CONSTRAINT "PK_association"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_association_class" ON association (parent_id ASC)
;

ALTER TABLE attribute ADD CONSTRAINT "PK_attribute"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_attribute_class" ON attribute (class_id ASC)
;

ALTER TABLE class ADD CONSTRAINT "PK_class"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_class_rdfs" ON class (rdfs_id ASC)
;

ALTER TABLE enum ADD CONSTRAINT "PK_enum"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_enum_rdfs" ON enum (rdfs_id ASC)
;

ALTER TABLE enumvalue ADD CONSTRAINT "PK_enumvalue"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_enumvalue_enum" ON enumvalue (enum_id ASC)
;

ALTER TABLE rdfs ADD CONSTRAINT "PK_rdfs"
	PRIMARY KEY (id)
;

ALTER TABLE rdfsattribute ADD CONSTRAINT "PK_rdfsattribute"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_rdfsattribute_rdfs" ON rdfsattribute (rdfs_id ASC)
;

ALTER TABLE subclass ADD CONSTRAINT "PK_subclass"
	PRIMARY KEY (master_id,sub_id)
;

CREATE INDEX "IXFK_subclass_class" ON subclass (master_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE association ADD CONSTRAINT "FK_association_class"
	FOREIGN KEY (parent_id) REFERENCES class (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE attribute ADD CONSTRAINT "FK_attribute_class"
	FOREIGN KEY (class_id) REFERENCES class (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE class ADD CONSTRAINT "FK_class_rdfs"
	FOREIGN KEY (rdfs_id) REFERENCES rdfs (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE enum ADD CONSTRAINT "FK_enum_rdfs"
	FOREIGN KEY (rdfs_id) REFERENCES rdfs (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE enumvalue ADD CONSTRAINT "FK_enumvalue_enum"
	FOREIGN KEY (enum_id) REFERENCES enum (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE rdfsattribute ADD CONSTRAINT "FK_rdfsattribute_rdfs"
	FOREIGN KEY (rdfs_id) REFERENCES rdfs (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE subclass ADD CONSTRAINT "FK_subclass_class"
	FOREIGN KEY (master_id) REFERENCES class (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE association_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE attribute_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE class_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE enum_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE enumvalue_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE rdfs_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE rdfsattribute_id_seq INCREMENT 1 START 1
;


CREATE OR REPLACE PROCEDURE insert_rdfs(rdftype VARCHAR(100),
                                version VARCHAR(50),
								INOUT ret_id bigint)
LANGUAGE plpgsql
AS $$
BEGIN
	INSERT INTO rdfs(rdftype,
						version,
						created_time)
	VALUES ($1,
            $2,
			CURRENT_TIMESTAMP)
	RETURNING rdfs.id INTO ret_id;
END;
$$;

CREATE OR REPLACE PROCEDURE insert_rdfsattribute(atname VARCHAR(100),
											atvalue TEXT,
											rdfs_id BIGINT)
LANGUAGE plpgsql
AS $$
BEGIN
	INSERT INTO rdfsattribute(name,
						value,
						rdfs_id)
	VALUES ($1,
            $2,
			$3);
END;
$$;

CREATE OR REPLACE PROCEDURE insert_class(clname VARCHAR(100),
                                cllabel VARCHAR(100),
								clcomment TEXT,
								rdfs_id BIGINT,
								INOUT ret_id bigint)
LANGUAGE plpgsql
AS $$
BEGIN
	INSERT INTO class(name,
						label,
						comment,
						rdfs_id)
	VALUES ($1,
            $2,
			$3,
			$4)
	RETURNING class.id INTO ret_id;
END;
$$;

CREATE OR REPLACE PROCEDURE insert_association(parentid bigint,
												childid bigint,
												asname VARCHAR(100),
                                				aslabel VARCHAR(100),
												mumin integer,
												mumax integer,
												ascomment TEXT,
												asrange VARCHAR(100),
												inverserole VARCHAR(100),
												used boolean,
												INOUT ret_id bigint)
LANGUAGE plpgsql
AS $$
BEGIN
	INSERT INTO association(parent_id,
						child_id,
						name,
						label,
						multimin,
						multimax,
						comment,
						range,
						inverserole,
						used)
	VALUES ($1,
            $2,
			$3,
			$4,
			$5,
			$6,
			$7,
			$8,
			$9,
			$10)
	RETURNING association.id INTO ret_id;
END;
$$;

CREATE OR REPLACE PROCEDURE insert_attribute(classid bigint,
												atname VARCHAR(100),
                                				atlabel VARCHAR(100),
												datatype VARCHAR(100),
												atcomment TEXT,
												mandatory boolean,
												INOUT ret_id bigint)
LANGUAGE plpgsql
AS $$
BEGIN
	INSERT INTO attribute(class_id,
							name,
							label,
							datatype,
							comment,
							mandatory)
	VALUES ($1,
            $2,
			$3,
			$4,
			$5,
			$6)
	RETURNING attribute.id INTO ret_id;
END;
$$;

CREATE OR REPLACE PROCEDURE insert_enum(enname VARCHAR(100),
                                		enlabel VARCHAR(100),
										encomment TEXT,
										rdfsid BIGINT,
										INOUT ret_id bigint)
LANGUAGE plpgsql
AS $$
BEGIN
	INSERT INTO enum(name,
						label,
						comment,
						rdfs_id)
	VALUES ($1,
            $2,
			$3,
			$4)
	RETURNING enum.id INTO ret_id;
END;
$$;

CREATE OR REPLACE PROCEDURE insert_enumvalue(enumid BIGINT,
											evname VARCHAR(100),
											encomment TEXT)
LANGUAGE plpgsql
AS $$
BEGIN
	INSERT INTO enumvalue(enum_id,
						name,
						comment)
	VALUES ($1,
            $2,
			$3);
END;
$$;

CREATE OR REPLACE PROCEDURE insert_subclass(masterid BIGINT,
											subid BIGINT)
LANGUAGE plpgsql
AS $$
BEGIN
	INSERT INTO subclass(master_id,
						sub_id)
	VALUES ($1,
            $2);
END;
$$;


